#!/usr/bin/env python
import sys, os
import cgi, cgitb
import anydbm
import time, datetime
try: from cgi import parse_qs
except: from urlparse import parse_qs

cgitb.enable()
DBMFILE = '/tmp/ipguards.db'

def authenticate(username, password):
	if username == 'test' and password == 'config': return True
	return False

def expire_to_minutes(s):
	p = s.split(':')
	p.reverse()
	minutes = int(p[0])
	if len(p) >= 2: minutes += int(p[1]) * 60
	if len(p) >= 3: minutes += int(p[2]) * 60 * 24
	return minutes

def update_db(username, ipaddr, expire_minutes):
	now = time.time()
	active_time = time.gmtime(now)
	expire_time = time.gmtime(now + expire_minutes * 60)
	active_time = time.strftime('%Y-%m-%d %H:%M:%S', active_time)
	expire_time = time.strftime('%Y-%m-%d %H:%M:%S', expire_time)

	db = anydbm.open(DBMFILE, 'c', 0600)
	db[username] = 'ipaddr=%s; time=%s; expire=%s' % (ipaddr, active_time, expire_time)
	db.close()
	return expire_time

def display_form():
	ipaddr = os.environ['REMOTE_ADDR']
	print '<form method="post" action="?action=submit">'
	print '<p>Username: <input type="text" name="username"></p>'
	print '<p>Password: <input type="password" name="password"></p>'
	print '<p>IP Address: <input type="text" name="ipaddr" value="%s"></p>' % ipaddr
	print '<p>Expire Time: <input type="text" name="expire" value="1:00"></p>'
	print '<p><input type="submit"></p>'
	print '</form>'

def submit_form():
	form = cgi.FieldStorage()
	username = form.getvalue('username')
	if not authenticate(username, form.getvalue('password')):
		return display_form()
	expire_minutes = expire_to_minutes(form.getvalue('expire'))
	expire_time = update_db(username, form.getvalue('ipaddr'), expire_minutes)
	print 'Access Granted until %s GMT' % expire_time

def main():
	print 'Content-Type: text/html'
	print
	qs = parse_qs(os.environ['QUERY_STRING'])
	action = qs.get('action')
	if action: action = action[0]
	if action == 'submit': submit_form()
	else: display_form()

if __name__ == '__main__': main()
