#!/usr/bin/env python
import os
import time
import socket
import simplejson
import cgi, cgitb
try: from cgi import parse_qs
except: from urlparse import parse_qs

cgitb.enable()
SOCKFILE = '/tmp/ipguards.sock'

def html_encode(s):
	s = s.replace('&','&amp;')
	s = s.replace('<','&lt;').replace('>','&gt;')
	return s

def ttl_to_seconds(s):
	p = s.split(':')
	p.reverse()
	minutes = int(p[0])
	if len(p) >= 2: minutes += int(p[1]) * 60
	if len(p) >= 3: minutes += int(p[2]) * 60 * 24
	return minutes * 60

def send_request(cmd, data):
	s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM, 0)
	s.connect(SOCKFILE)
	try:
		sf = s.makefile('r+')
		sf.write('%s %s\n' % (cmd, simplejson.dumps(data)))
		sf.flush()
		line = sf.readline().strip()
		try: code,data = line.split(' ', 1)
		except: code,data = line,''
		data = simplejson.loads(data)
	finally:
		sf.close()

	return code,data

def display_form():
	ipaddr = os.environ['REMOTE_ADDR']
	print '<form method="post" action="?action=submit">'
	print '<p>Username: <input type="text" name="username"></p>'
	print '<p>Password: <input type="password" name="password"></p>'
	print '<p>IP Address: <input type="text" name="ipaddr" value="%s"></p>' % ipaddr
	print '<p>Time-To-Live: <input type="text" name="ttl" value="1:00"></p>'
	print '<p><input type="submit"></p>'
	print '</form>'

def submit_form():
	form = cgi.FieldStorage()
	data = dict([(x,form.getvalue(x)) for x in ('username','password','ipaddr')])
	data['ttl'] = ttl_to_seconds(form.getvalue('ttl'))
	code,data = send_request('GRANT', data)
	if code == 'OK':
		expire_time = time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(data['expire']))
		print 'Access Granted for %s until %s' % (data['ipaddr'], expire_time)
	else:
		print 'Error:', html_encode(str(data))

def main():
	print 'Content-Type: text/html'
	print
	qs = parse_qs(os.environ['QUERY_STRING'])
	action = qs.get('action')
	if action: action = action[0]
	if action == 'submit': submit_form()
	else: display_form()

if __name__ == '__main__': main()
